export enum AssetTransferTypeEnum {
    FUND_SFUTURES = 'FUND_SFUTURES',
    SFUTURES_FUND = 'SFUTURES_FUND',
    FUND_PFUTURES = 'FUND_PFUTURES',
    PFUTURES_FUND = 'PFUTURES_FUND',
    SFUTURES_PFUTURES = 'SFUTURES_PFUTURES',
    PFUTURES_SFUTURES = 'PFUTURES_SFUTURES',
    FUND_STRADING = 'FUND_STRADING',
    STRADING_FUND = 'STRADING_FUND',
    FUND_CTRADING = 'FUND_CTRADING',
    SFUTURES_CTRADING = 'SFUTURES_CTRADING',
    PFUTURES_CTRADING = 'PFUTURES_CTRADING',
    CTRADING_FUND = 'CTRADING_FUND',
    CTRADING_SFUTURES = 'CTRADING_SFUTURES',
    CTRADING_PFUTURES = 'CTRADING_PFUTURES'
}

export enum AccountTypeEnum {
    SPOT = 'sopt',
    WEALTH = 'eran',
    STANDARD_FUTURES = 'stdFutures',
    COIN_BASE = 'coinMPerp',
    USDT_BASE = 'USDTMPerp',
    COPY_TRADING = 'copyTrading',
    GRID = 'grid',
    C2C = 'c2c'
}
