export enum AssetTransferTypeEnum {
    FUND_SFUTURES = 'FUND_SFUTURES',
    SFUTURES_FUND = 'SFUTURES_FUND',
    FUND_PFUTURES = 'FUND_PFUTURES',
    PFUTURES_FUND = 'PFUTURES_FUND',
    SFUTURES_PFUTURES = 'SFUTURES_PFUTURES',
    PFUTURES_SFUTURES = 'PFUTURES_SFUTURES',
    FUND_STRADING = 'FUND_STRADING',
    STRADING_FUND = 'STRADING_FUND',
    FUND_CTRADING = 'FUND_CTRADING',
    SFUTURES_CTRADING = 'SFUTURES_CTRADING',
    PFUTURES_CTRADING = 'PFUTURES_CTRADING',
    CTRADING_FUND = 'CTRADING_FUND',
    CTRADING_SFUTURES = 'CTRADING_SFUTURES',
    CTRADING_PFUTURES = 'CTRADING_PFUTURES'
}
